repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black (Projekt)
        args: [Projekt]
        pass_filenames: false
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 (Projekt)
        args: [Projekt]
        pass_filenames: false
